### PR TITLE
I18n

### PR DESCRIPTION
**Pull request by isaacseymour**
My fabulous translation skills could probably use some boosting from @octaveauger 

@greysteil could you review the codes? I don't think we need to translate the error messages which get raised as they shouldn't be shown to an end user (I don't think?).

### CODE REVIEW

**Comment by greysteil** [comment]
Worth speccing the interpolated strings. Otherwise :+1:

**Comment by isaacseymour** [comment]
Added some more specs. Will update them with real translations later, then merge unless you have objections @greysteil ?

**Comment by greysteil** [comment]
:+1: after some French.

**Comment by isaacseymour** [comment]
@greysteil could you push a new version to RubyGems when you have a minute?

**Comment by greysteil** [comment]
@isaacseymour - done. Nice work on this.

**Pull request merged**
